Neos:
  Neos:
    fusion:
      autoInclude:
        ObisConcept.CookieConsent: true

ObisConcept:
  CookieConsent:
    enable: true
    includeJavaScript: true
    includeCss: true
    translations:
      package: 'ObisConcept.CookieConsent'
      source: 'Main'
    settings:
      type: 'notice'
      position: 'bottom'
      theme: 'block'
      policyPage:
        node: ''
        section: ''
      palette:
        popup:
          background: '#000'
          text: '#fff'
        button:
          background: '#f1d600'
          text: '#000'
